### ISSUE TITLE
This repo might be obsolete => use -webkit-backdrop-filter

### ISSUE THREAD

**Issue by ertogs** [ionic-team/ionic-contrib-frosted-glass#12]
We can now use <b>-webkit-backdrop-filter</b> in current iOS 9
So I think there is no need for javascript anymore.

``` css
.bar-frosted {
    background-color: rgba(255, 255, 255, 0.2);
    -webkit-backdrop-filter:blur(20px);
    border-bottom:1px solid #dddddd;
}


```
